ALTER TABLE `users` 
ADD COLUMN IF NOT EXISTS `skin` LONGTEXT NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `tattoos` LONGTEXT NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `face_features` LONGTEXT NULL DEFAULT NULL;
